debug: false


cache_file: './pretrain/resnet50-19c8e357.pth'
logs_dir: '/home/huangjinze/code/PTKP/logs/TMTncforgetpartKD_P_kd_NA'
logfilename: 'TMTncforgetpartKD_P_kd_NA'
# ========================== data ==========================#
data_dir: '/home/huangjinze/data/REID'
batch_size: 32 #128
replay_batch_size: 128
workers: 4
height: 256
width: 128
num_instances: 4
data_aug:
  - DO_FLIP
  - DO_PAD
  - DO_NORM
  - REA_ENABLED
FLIP_PROB: 0.5

PADDING: 10
PADDING_MODE: constant

CJ_PROB: 0.8
CJ_BRIGHTNESS: 0.15
CJ_CONTRAST: 0.15
CJ_SATURATION: 0.1
CJ_HUE: 0.1

REA_PROB: 0.5
REA_MEAN:
  - 0.485
  - 0.456
  - 0.406

RPT_PROB: 0.5

NORM_MEAN:
  - 0.485
  - 0.456
  - 0.406
NORM_STD:
  - 0.229
  - 0.224
  - 0.225

# ========================== model ==========================#
backbone: ResNet
train_domain_num: 4
header: ncforgetpart
use_TSBN: true
post_process: false
neck_norm: CN # CN, BN, MetaBN
features: 0
dropout: 0
init_new_header: center #'center, SVD'

part_dim: 256
num_parts: 5

# ========================== optimizer ==========================#
lr: 0.00035
momentum: 0.9
weight_decay: 0.0005
warmup_step: 10

# ========================== testing configs ==========================#
evaluate: true
use_gpu: true
# ========================== training configs ==========================#
resume: true
use_replay: true
epochs: 60
iters: 210
seed: 42
print_freq: 200
margin: 0.3
loss_items:
  - tr
  - ce
  - sce
#  - sce0
#  - sce1
#  - sce2
  - replay_tr
  - DCL
  - PT_ID
  - PT_KD
  - nonlap
  - part_tr
  - part_ce
  - kd_part
  - kd_part0
  - kd_part1
  - kd_part2
#  - kd_assign
  - kd_assign0
  - kd_assign1
  - kd_assign2
#  - kd_new
#  - kd_part_new
# ========================== visualize ==========================#
visualize_train_by_visdom: false
VISUALIZE_NUM: 100
port: 8098